language: rust
cache: cargo
script:
  - cargo install mdbook --vers '^0.3.0' || true
  - bash bin/build.sh
deploy:
  provider: script
  script: bash bin/deploy.sh
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
    - master
